set_types:
  - deciles
n:
  - 10000
m:
  - 2
  - 4
  - 8
  - 16
item_len:
  - 3
  - 5
overlap_fraction:
  - null
  - 0.5
decile_group:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
swap_status:
  - false
